Update README.md
Need to add to the Scope for ti_crowdstrike IOC. To also have 'ioc-management:read' otherwise it results in 403  (access denied, authorization failed)

cel-ti_crowdstrike.ioc component state degraded, with 
```
error: 'single event error object returned by evaluation: {"error":{"code":"403","id":"403 Forbidden","message":"GET:{\n \"meta\": {\n  \"query_time\": 2.08e-7,\n  \"powered_by\": \"crowdstrike-api-gateway\",\n  \"trace_id\": \"8ad80abe-39e3-4b77-abb2-aefe3fc4037c\"\n },\n \"errors\": [\n  {\n   \"code\": 403,\n   \"message\": \"access denied, authorization failed\"\n  }\n ]\n}"}}'
```

For example from agent (debug) logs
```
{"log.level":"debug","@timestamp":"2025-03-21T13:10:57.138Z","message":"response state","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"id":"cel-ti_crowdstrike.ioc-54d15ceb-4cde-44d0-8ef3-a24a6877cda0","input_url":"https://api.us-2.crowdstrike.com","log.origin":{"file.line":254,"file.name":"cel/input.go","function":"github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1"},"log.logger":"input.cel","service.name":"filebeat","input_source":"https://api.us-2.crowdstrike.com","cel":{"ecs.version":"1.6.0","state":"{\"batch_size\":2000,\"events\":{\"error\":{\"code\":\"403\",\"id\":\"403 Forbidden\",\"message\":\"GET:{\\n \\\"meta\\\": {\\n  \\\"query_time\\\": 2.23e-7,\\n  \\\"powered_by\\\": \\\"crowdstrike-api-gateway\\\",\\n  \\\"trace_id\\\": \\\"eebad11e-fba0-460b-abd7-e7b6a4613a75\\\"\\n },\\n \\\"errors\\\": [\\n  {\\n   \\\"code\\\": 403,\\n   \\\"message\\\": \\\"access denied, authorization failed\\\"\\n  }\\n ]\\n}\"}},\"initial_interval\":\"24h\",\"offset\":0,\"url\":\"https://api.us-2.crowdstrike.com\",\"want_more\":false}"},"ecs.version":"1.6.0"}
```

Related KB  https://support.elastic.co/knowledge/8703a71e