Add system and pipeline tests for Zoom
Changes:

- Remove logfile input. It was only needed for testing purposes, but we are now testing via pipeline and webhook callbacks.
- Remove prefix config option. Changing the value would break the pipeline.
- Add url config option.
- Fix basic auth parameters in handlebar template (missing password option, and username was set to password).
- Add missing field definition for input.type.

Remaining issues:

```
FAILURE DETAILS:

zoom/webhook test-chat-message.json:
[0] parsing field value failed: field "zoom.chat_message.message"'s Go type, <nil>, does not match the expected field type: keyword (field value: <nil>)
zoom/webhook test-phone.json:
[0] parsing field value failed: field "zoom.phone.duration"'s Go type, string, does not match the expected field type: long (field value: 1235)

ERROR: simulating pipeline processing failed: unexpected response status for Simulate (400): 400 Bad Request: elasticsearch error (type=illegal_argument_exception): field [members] not present as part of path [zoom.chat_channel.members]
```