Disable nats/route data_stream system test
I think this one fails because of the testing service sending a single
UDP packet which may be sent before the elastic-agent is listening.

--- Test results for package: nats - START ---
╭─────────┬───────────────┬───────────┬───────────┬────────────────────────────────────────────────────────────────┬────────────────╮
│ PACKAGE │ DATA STREAM   │ TEST TYPE │ TEST NAME │ RESULT                                                         │   TIME ELAPSED │
├─────────┼───────────────┼───────────┼───────────┼────────────────────────────────────────────────────────────────┼────────────────┤
│ nats    │ connection    │ system    │ default   │ PASS                                                           │ 1m2.813631747s │
│ nats    │ connections   │ system    │ default   │ PASS                                                           │  18.417229473s │
│ nats    │ log           │ system    │ default   │ PASS                                                           │  26.932125276s │
│ nats    │ route         │ system    │ default   │ FAIL: could not find hits in metrics-nats.route-ep data stream │ 2m20.71934469s │
│ nats    │ stats         │ system    │ default   │ PASS                                                           │  18.361126482s │
│ nats    │ subscriptions │ system    │ default   │ PASS                                                           │  18.462041002s │
╰─────────┴───────────────┴───────────┴───────────┴────────────────────────────────────────────────────────────────┴────────────────╯

FAILURE DETAILS:

nats/route default:

--- Test results for package: nats - END   ---
Done
Error: one or more test cases failed