fix(okta): prevent pagination when response len is under limit
Optimize the Okta integration by stopping pagination requests when the
API returns fewer logs than the requested limit. This prevents redundant
API calls that would return empty (or non-full) responses and consume
rate-limit tokens unnecessarily.

A new 'limit' variable had to be added to enable testing of this change.
If 'limit' were not configurable, then the test must generate >1000
events to validate that the "next" link was followed. However, the
'assert.hit_count' feature does not allow assertions beyond 500. It
errors with:

    ERROR: invalid value for assert.hit_count (1002):
    it must be lower of the maximum query size (500)

For system tests using the 'okta-oauth2' service, 'limit: 1' was set
to make the tests continue requesting data if anything event was returned.
The mock does not utilize or honor the limit.

Fixes #15212