Update kibana.constraint
I tested with 8.3.2 and it works when upgrading from 1.4.1 to 1.5.0 (this version).

With 7.17.6-SNAPHOT it fails during the policy upgrade with

    Error: Root value is not flatten-able, received undefined